name: Create or Update a Git Tag
description: >
  Create or update a git tag.
  Only update the git tag if the message of the git tag is changed.

  This is useful if you are trying to store some data within a git tag message.

  NOTE: Will force update the git tag if an update is required.
inputs:
  tag-name:
    description: Git tag to create or update.
    required: true
  tag-message:
    description: Message to add to the tag.
    required: true
env:
  remote: origin


runs:
  using: composite
  steps:
    - name: debug
      run: |
        echo "${{steps.existing-message.outputs.result}}"
        echo "${{github.event.inputs.tag-message}}"
        echo "${{steps.existing-message.outputs.result != github.event.inputs.tag-message}}"
        echo $TAG1
        echo $TAG2
        echo $TAG3
        echo $MSG1
        echo $MSG2
        echo $MSG3
      shell: bash
      env:
        TAG1: ${{ inputs.tag-name }}
        TAG2: ${{ github.events.inputs.tag-name }}
        TAG3: ${{ env.tag-name }}
        MSG1: ${{ inputs.tag-message }}
        MSG2: ${{ github.events.tag-message }}
        MSG3: ${{ env.tag-message }}
    - name: Get all tags within repository
      run: git fetch --tags --prune-tags
      shell: bash
    - name: Get existing tag message
      id: existing-message
      run: >
        echo "result=$(
        git tag --list --format='%(contents)' $TAG
        )" >> $GITHUB_OUTPUT
      shell: bash
      env:
        TAG: ${{ inputs.tag-name }}
    - name: debug
      run: |
        echo "${{steps.existing-message.outputs.result}}"
        echo "${{github.event.inputs.tag-message}}"
        echo "${{steps.existing-message.outputs.result != github.event.inputs.tag-message}}"
        echo $TAG1
        echo $TAG2
        echo $TAG3
        echo $MSG1
        echo $MSG2
        echo $MSG3
      shell: bash
      env:
        TAG1: ${{ inputs.tag-name }}
        TAG2: ${{ github.events.inputs.tag-name }}
        TAG3: ${{ env.tag-name }}
        MSG1: ${{ inputs.tag-message }}
        MSG2: ${{ github.events.tag-message }}
        MSG3: ${{ env.tag-message }}
    - name: Create or Update if required
      if: steps.existing-message.outputs.result != github.event.inputs.tag-message
      run: |
        git tag --force --message="$MESSAGE" "$TAG" $(git rev-parse HEAD)
        git push --force  "$REMOTE" "$TAG"
      env:
        REMOTE: ${{ env.remote }}
        TAG: ${{ github.event.inputs.tag-name }}
        MESSAGE: ${{ github.event.inputs.tag-message }}
      shell: bash
