name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  test-message: "  AA BB CC DEADBEEF!!  "
  test-tag: test-tag/${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  test-bash:
    permissions: write-all
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          tag-name: "${{ env.test-tag }}"
          tag-message: "${{ env.test-message }}"
      - run: test "$(git tag --list --format='%(contents)')" = "${{ github.env.test-message }}"

  # test-powershell:
  #   strategy:
  #     fail-fast: false
  #   runs-on: windows
  #   timeout-minutes: 5

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./action.yml
  #       with:
  #         tag-name: ${{ github.env.test-tag }}
  #         tag-message: ${{ github.env.test-message }}
  #     - run: test "$(git tag --list --format='%(contents)')" = "${{ github.env.test-message }}"

  # # Make up matrix statuses into a status for status checks in branch protection rules
  # test-passing:
  #   needs: [ test-bash, test-powershell ]
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 1

  #   steps:
  #     - run: echo "All tests have passed."
