name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  test-message: "  AA BB CC DEADBEEF!!  "
  test-tag: test-tag/${{ github.run_id }}-${{ github.run_attempt }}


jobs:
  runners:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.list.outputs.all }}
      windows: ${{ steps.list.outputs.windows }}
    steps:
      - id: list
        uses: snow-actions/list-github-hosted-runners@v1.0.0

  test-bash:
    needs: [ runners ]
    strategy:
      fail-fast: false
      matrix:
        # Runs on all supported runners
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        runner: ${{ fromJSON(needs.runners.outputs.all) }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 5
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: ./action.yml
        with:
          tag-name: ${{ github.env.test-tag }}
          tag-message: ${{ github.env.test-message }}
      - run: test "$(git tag --list --format='%(contents)')" = "${{ github.env.test-message }}"

  test-powershell:
    needs: [ runners ]
    strategy:
      fail-fast: false
      matrix:
        runner: ${{ fromJSON(needs.runners.outputs.windows) }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: ./action.yml
        with:
          tag-name: ${{ github.env.test-tag }}
          tag-message: ${{ github.env.test-message }}
      - run: test "$(git tag --list --format='%(contents)')" = "${{ github.env.test-message }}"

  # Make up matrix statuses into a status for status checks in branch protection rules
  test-passing:
    needs: [ test-bash, test-powershell ]
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: echo "All tests have passed."
